### PR TITLE
Modify the Soak Tests for ADOT JS Downstream

### PR DESCRIPTION
**Pull request by NathanielRN**
# Description

Modifies the [AWS OTel Python Soaking Tests](https://github.com/aws-observability/aws-otel-python/blob/main/.github/workflows/soak-testing.yml) for using in the AWS OTel JS repo.

### CODE REVIEW

**Comment by NathanielRN** [comment]
Finished [a successful run of the Soak Tests](https://github.com/NathanielRN/aws-otel-js/runs/3669788559?check_suite_focus=true) on my personal fork.

Got the following snapshot results:

CPU THRESHOLD
MEMORY

JS, like go, was on the low end in these performance results. That's why we chose a CPU load of 65 and memory limit of 1.5 GiB. It might be worth it to wait for the next run that finishes at 1pm PST, but this is what drove the numbers in this PR!

**Review by willarmiros — APPROVED** [review]
LGTM

**Comment by NathanielRN** [comment]
Closing because https://github.com/aws-observability/aws-otel-js/pull/65 was merged.

**Comment by NathanielRN** [comment]
The diff is wrong and unrecoverable, refer to https://github.com/NathanielRN/aws-otel-js/pull/2 to learn what the differences were.

**Pull request closed without merging**
